"""
Regenerate incumbent baselines in the same harness as the Mode B runs.

Computes, per (workload, cache), the schedules and exact-sim metrics for
the demo-paper comparison set:

- ``greedy_d``   nearest-neighbour on the directional matrix
- ``ga_m``       GA with symmetric approximate fitness (paper-style)
- ``ga_d``       GA with single-step directional approximate fitness

Every method is scored by the same exact clock-sweep simulator, on the
same page-access profiles, at the same cache size, with the same cost
definition (1 − F_hit) used by the BO trial logs — so baseline and BO
numbers are directly comparable and no stale results from earlier
sweeps are ever mixed in.  The equal-budget random comparison is *not*
a baseline here: it runs as the ``random`` backend of the BO runner so
that it shares the BO arms' budgets and logging.

Usage
-----
    python -m src.bayesopt.run_baselines \\
        --workload tpch --cache-pages 102400 \\
        --page-access-dir page_access/tpch_6gb --seed 42
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

from src.bayesopt.data import load_workload_pages
from src.bayesopt.objective import EvalMetrics, ExactSimObjective
from src.bayesopt.priority import is_valid_permutation
from src.scheduler.genetic_algorithm import run_ga
from src.scheduler.genetic_config import ApproxMode, GAConfig
from src.scheduler.greedy_directional import greedy_directional_schedule
from src.simulator.access_profile import AccessProfile
from src.simulator.cache_simulator import compute_directional_matrix
from src.utilities.constants import PROJECT_ROOT, WORKLOAD_DIRS

BASELINE_METHODS = ("greedy_d", "ga_m", "ga_d")
"""Incumbent baseline methods regenerated by this runner."""


def _stub_profiles(query_ids: list[str]) -> list[AccessProfile]:
    """
    Minimal AccessProfile stubs for page-level GA runs.

    With ``use_approximate_fitness=True`` and page_sets supplied, the GA
    never reads ``table_pages``; profiles only provide the query count
    and ids, so empty stubs are sufficient and keep this runner DB-free.
    """
    return [AccessProfile(query_id=qid) for qid in query_ids]


def _ga_config(
    cache_pages: int,
    approx_mode: ApproxMode,
    seed: int,
    population: int,
    generations: int,
) -> GAConfig:
    """Production-style GA configuration on the page-level approximate path."""
    return GAConfig(
        population_size=population,
        num_generations=generations,
        cache_capacity_pages=cache_pages,
        seed=seed,
        use_approximate_fitness=True,
        approx_mode=approx_mode,
    )


def compute_baseline_schedule(
    method: str,
    page_sets: list[frozenset[int]],
    query_ids: list[str],
    d_matrix: list[list[int]],
    cache_pages: int,
    seed: int,
    population: int,
    generations: int,
) -> list[int]:
    """
    Compute one baseline schedule.

    Parameters
    ----------
    method : str
        One of :data:`BASELINE_METHODS`.
    page_sets : list[frozenset[int]]
        Integer-encoded per-query page sets.
    query_ids : list[str]
        Query ids aligned with *page_sets*.
    d_matrix : list[list[int]]
        Directional matrix at *cache_pages* (used by ``greedy_d``).
    cache_pages : int
        Clock-sweep cache capacity in pages.
    seed, population, generations : int
        GA settings for the ``ga_m`` / ``ga_d`` methods.

    Returns
    -------
    list[int]
        A permutation of all query indices.
    """
    if method == "greedy_d":
        page_counts = [len(ps) for ps in page_sets]
        schedule = greedy_directional_schedule(d_matrix, page_counts)
    elif method in ("ga_m", "ga_d"):
        approx: ApproxMode = "symmetric" if method == "ga_m" else "directional"
        result = run_ga(
            _stub_profiles(query_ids),
            _ga_config(cache_pages, approx, seed, population, generations),
            page_sets=page_sets,
        )
        schedule = result.best_schedule
    else:
        raise ValueError(f"unknown baseline method {method!r}")

    if not is_valid_permutation(schedule, len(page_sets)):
        raise RuntimeError(f"{method} produced an invalid schedule: {schedule}")
    return schedule


def build_parser() -> argparse.ArgumentParser:
    """Construct the CLI argument parser."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--workload", choices=list(WORKLOAD_DIRS), required=True)
    parser.add_argument("--cache-pages", type=int, required=True)
    parser.add_argument(
        "--page-access-dir", type=Path, required=True,
        help="Per-query page-access CSV directory (use the _6gb dirs).",
    )
    parser.add_argument(
        "--methods", default=",".join(BASELINE_METHODS),
        help=f"Comma-separated subset of {BASELINE_METHODS}.",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--ga-population", type=int, default=100)
    parser.add_argument("--ga-generations", type=int, default=200)
    parser.add_argument("--exclude", default="")
    parser.add_argument(
        "--out-dir", type=Path,
        default=PROJECT_ROOT / "experiment_logs" / "bo",
    )
    return parser


def main(argv: list[str] | None = None) -> None:
    """Regenerate the requested baselines for one (workload, cache)."""
    args = build_parser().parse_args(argv)
    methods = [m.strip() for m in args.methods.split(",") if m.strip()]
    unknown = set(methods) - set(BASELINE_METHODS)
    if unknown:
        raise SystemExit(f"unknown methods: {sorted(unknown)}")

    exclude = {q.strip() for q in args.exclude.split(",") if q.strip()}
    print(f"Loading page sets from {args.page_access_dir}…")
    wp = load_workload_pages(args.page_access_dir, exclude=exclude)
    print(
        f"  {wp.n} queries, {wp.total_unique_pages:,} unique pages, "
        f"cache C = {args.cache_pages:,} pages"
    )

    t0 = time.perf_counter()
    d_matrix = compute_directional_matrix(wp.page_sets, args.cache_pages)
    print(f"  Directional matrix in {time.perf_counter() - t0:.1f}s")
    objective = ExactSimObjective(
        wp.page_sets, args.cache_pages, d_matrix=d_matrix
    )
    args.out_dir.mkdir(parents=True, exist_ok=True)

    rows: list[tuple[str, EvalMetrics, float]] = []
    for method in methods:
        t0 = time.perf_counter()
        schedule = compute_baseline_schedule(
            method, wp.page_sets, wp.query_ids, d_matrix,
            args.cache_pages, args.seed,
            args.ga_population, args.ga_generations,
        )
        scheduler_seconds = time.perf_counter() - t0
        metrics, _ = objective.evaluate_schedule(schedule)
        rows.append((method, metrics, scheduler_seconds))

        summary: dict[str, object] = {
            "workload": args.workload,
            "cache_pages": args.cache_pages,
            "page_access_dir": str(args.page_access_dir),
            "mode": "baseline",
            "method": method,
            "seed": args.seed,
            "ga_population": args.ga_population,
            "ga_generations": args.ga_generations,
            "n_queries": wp.n,
            "excluded": sorted(exclude),
            "schedule": schedule,
            "schedule_qids": [wp.query_ids[i] for i in schedule],
            "sim_hit_ratio": metrics.hit_ratio,
            "cost": metrics.cost,
            "sim_hits": metrics.total_hits,
            "sim_requests": metrics.total_requests,
            "sim_page_reads": metrics.page_reads,
            "edge_sum_d": metrics.edge_sum_d,
            "scheduler_seconds": round(scheduler_seconds, 3),
        }
        stem = (
            f"{args.workload}_c{args.cache_pages}_baseline_{method}"
            f"_s{args.seed}"
        )
        with open(args.out_dir / f"{stem}.summary.json", "w") as f:
            json.dump(summary, f, indent=2)
        print(
            f"  {method:9s} F_hit={metrics.hit_ratio:7.4f}  "
            f"reads={metrics.page_reads:>12,}  "
            f"sched={scheduler_seconds:7.1f}s",
            flush=True,
        )

    best = max(rows, key=lambda r: r[1].hit_ratio)
    print(f"\nBest baseline at C={args.cache_pages:,}: {best[0]} "
          f"(F_hit {best[1].hit_ratio:.4f})")
    print(f"Summaries in {args.out_dir}", file=sys.stderr)


if __name__ == "__main__":
    main()
