// Objective 3: explain a selected GENERATED schedule. Values come from offline
// construction metadata generated from the research scheduler; nothing is
// inferred in the browser.

import { Api } from "./api.js";
import { int, pct } from "./format.js";

export class ExplainView {
  constructor({ mount, workloads, presets }) {
    this.mount = mount;
    this.workloads = workloads;
    this.presets = presets;
    this.workload = workloads[0]?.name || "tpch";
    this.capacity = presets[0]?.pages || 102400;
    this.method = "sweep_D";
    this.data = null;
    this.selected = 0;
    this._token = 0;
    this._build();
  }

  _build() {
    this.mount.innerHTML = `
      <div class="section-title objective-head">
        <div><span class="objective-kicker">Objective 3</span><h2>Explaining Generated Schedules</h2></div>
        <p>Inspect a transition from a schedule actually generated by Queryosity. The explanation exposes directional reuse D[i,j;C], normalized reuse D̂[i,j], regret, and the construction score for the selected capacity.</p>
      </div>
      <div class="planning-controls panel panel--tight" id="explain-controls"></div>
      <div id="explain-body"></div>`;
    const controls = this.mount.querySelector("#explain-controls");
    this._wl = select(this.workloads.map((w) => [w.name, w.label]), this.workload, (v) => { this.workload = v; this.refresh(); });
    this._cap = select(this.presets.map((p) => [String(p.pages), `${int(p.pages)} pages · ${p.human}`]), String(this.capacity), (v) => { this.capacity = parseInt(v, 10); this.refresh(); });
    this._method = select([["sweep_D", "Sweep-D"], ["sweep_beam_D", "Sweep+Beam-D"]], this.method, (v) => { this.method = v; this.refresh(); });
    controls.append(field("Workload", this._wl), field("Buffer capacity C", this._cap), field("Generated method", this._method));
    this._body = this.mount.querySelector("#explain-body");
    this.refresh();
  }

  setContext(workload, cap, method) {
    if (this.workloads.some((w) => w.name === workload)) { this.workload = workload; this._wl.value = workload; }
    if (this.presets.some((p) => p.pages === cap)) { this.capacity = cap; this._cap.value = String(cap); }
    if (["sweep_D", "sweep_beam_D"].includes(method)) { this.method = method; this._method.value = method; }
    this.refresh();
  }

  async refresh() {
    const token = ++this._token;
    this.selected = 0;
    this._body.innerHTML = `<div class="notice">Loading recorded scheduler explanation…</div>`;
    try {
      const data = await Api.explanation(this.workload, this.capacity, this.method);
      if (token !== this._token) return;
      this.data = data; this._render();
    } catch (err) {
      if (token !== this._token) return;
      this._body.innerHTML = `<div class="notice ${err.status === 404 ? "" : "err-inline"}">${err.status === 404
        ? `No explanation artifact is prepared for this selection. Generate the real artifacts on the VM with <code>python scripts/generate_demo_artifacts.py --all</code>.`
        : `Could not load explanation: ${escapeHtml(err.message)}`}</div>`;
    }
  }

  _render() {
    const d = this.data;
    const x = d.explanation || {};
    const c = d.construction || {};
    const mock = d.backend === "mock" ? `<div class="callout warn demo-warning">MOCK mode: research construction metadata is intentionally not fabricated.</div>` : "";
    if (!x.available) {
      this._body.innerHTML = `${mock}<div class="schedule-summary panel">
        <div><span class="eyebrow">generated schedule</span><h3>${escapeHtml(d.label)}</h3></div>
        <div class="primary-metrics">${metric("Modeled hits", int(d.total_hits))}${metric("Modeled misses", int(d.total_misses))}${metric("F<sub>hit</sub>", pct(d.f_hit, 2), "metric-value--accent")}</div>
        <div class="order-ribbon">${(d.order || []).map((q, i) => `<span class="query-pill">${qid(q)}</span>${i < d.order.length - 1 ? `<span class="order-arrow">→</span>` : ""}`).join("")}</div>
      </div><div class="notice">${escapeHtml(x.reason || "Transition-level construction metadata is unavailable for this artifact.")}</div>`;
      return;
    }

    const beamText = c.beam_width ? `<span>beam width <b>${int(c.beam_width)}</b></span>` : "";
    this._body.innerHTML = `${mock}
      <div class="schedule-summary panel">
        <div class="schedule-summary__top">
          <div><span class="eyebrow">selected generated schedule</span><h3>${escapeHtml(d.label)}</h3></div>
          <div class="construction-tags"><span>wᵣ <b>${fmt(c.selected_w_regret)}</b></span>${beamText}<span>start <b>${qid(c.start_query || d.order?.[0])}</b></span></div>
        </div>
        <div class="primary-metrics">${metric("Modeled hits", int(d.total_hits))}${metric("Modeled misses", int(d.total_misses))}${metric("Complete-order F<sub>hit</sub>", pct(d.f_hit, 2), "metric-value--accent")}</div>
      </div>
      <div class="explain-layout">
        <section class="panel transition-panel">
          <div class="spread"><div><span class="eyebrow">selected schedule</span><h3>Choose a transition</h3></div><span class="mono-note">${int(d.order.length - 1)} transitions</span></div>
          <div class="transition-strip" id="transition-strip"></div>
          <div id="transition-detail"></div>
        </section>
        <aside class="panel semantics-panel">
          <span class="eyebrow">two different scores</span>
          <h3>Construction ≠ selection</h3>
          <div class="semantic-item"><b>Construction score</b><p>${escapeHtml(x.semantics?.construction_score || "Directional reuse and regret guide candidate construction.")}</p></div>
          <div class="semantic-arrow">↓</div>
          <div class="semantic-item semantic-item--accent"><b>Complete-order score</b><p>${escapeHtml(x.semantics?.complete_order_score || "Complete-order cache simulation determines F_hit and the retained candidate.")}</p></div>
        </aside>
      </div>`;

    this._strip = this._body.querySelector("#transition-strip");
    this._detail = this._body.querySelector("#transition-detail");
    this._renderStrip(); this._renderTransition();
  }

  _renderStrip() {
    const trans = this.data.explanation.transitions || [];
    this._strip.innerHTML = trans.map((t, i) => `<button class="transition-chip ${i === this.selected ? "is-active" : ""}" data-step="${i}"><span>${i + 1}</span>${qid(t.from)} → ${qid(t.to)}</button>`).join("");
    this._strip.querySelectorAll("[data-step]").forEach((b) => b.addEventListener("click", () => {
      this.selected = parseInt(b.getAttribute("data-step"), 10); this._renderStrip(); this._renderTransition();
    }));
  }

  _renderTransition() {
    const t = this.data.explanation.transitions[this.selected];
    if (!t) { this._detail.innerHTML = ""; return; }
    const isBeam = this.data.method === "sweep_beam_D";
    const role = t.transition_role || (isBeam ? "retained_beam_transition" : "greedy_transition");
    const roleLabel = role === "retained_beam_transition" ? "retained beam transition" : "greedy transition";
    const selectedMark = isBeam ? "retained path" : "selected";
    const altRows = (t.alternatives || []).map((a) => `<tr class="${a.selected ? "is-selected" : ""}">
      <td>${qid(a.successor)}${a.selected ? `<span class="selected-mark">${selectedMark}</span>` : ""}</td>
      <td class="num">${fmt(a.normalized_reuse, 5)}</td>
      <td class="num">${fmt(a.regret, 5)}</td>
      <td class="num">${fmt(a.transition_score, 5)}</td>
    </tr>`).join("");
    const altNote = isBeam
      ? `same-state edge scores · beam retention is cumulative · ${int(t.remaining_count)} successors available`
      : `same-state construction scores · ${int(t.remaining_count)} successors available`;
    this._detail.innerHTML = `
      <div class="transition-heading"><div><span class="eyebrow">selected transition</span><h3>${qid(t.from)} <span>→</span> ${qid(t.to)}</h3></div><span class="rank-chip">${roleLabel}</span></div>
      <div class="transition-metrics">
        ${smallMetric("Directional reuse D[i,j;C]", `${int(t.directional_reuse)} pages`)}
        ${smallMetric("Normalized reuse D̂[i,j]", fmt(t.normalized_reuse, 5))}
        ${smallMetric("Regret(i,j,U)", fmt(t.regret, 5))}
        ${smallMetric("Construction score S(i,j,U)", fmt(t.transition_score, 5), true)}
        ${smallMetric("Selected regret weight wᵣ", fmt(t.selected_w_regret))}
        ${t.beam_width ? smallMetric("Selected beam width", int(t.beam_width)) : ""}
      </div>
      <div class="explanation-text"><span class="eyebrow">why this transition appears</span><p>${escapeHtml(t.text)}</p></div>
      <div class="alternatives-head"><div><span class="eyebrow">same-state comparison</span><h4>Successor construction scores</h4></div><span class="mono-note">${altNote}</span></div>
      <div class="table-wrap"><table class="alternatives"><thead><tr><th>Successor</th><th>Normalized reuse D̂[i,j]</th><th>Regret</th><th>Construction score</th></tr></thead><tbody>${altRows}</tbody></table></div>`;
  }

}

function metric(label, value, cls = "") { return `<div class="primary-metric"><span>${label}</span><strong class="num ${cls}">${value}</strong></div>`; }
function smallMetric(label, value, accent = false) { return `<div class="transition-metric ${accent ? "is-accent" : ""}"><span>${label}</span><strong class="num">${value}</strong></div>`; }
function select(items, value, onChange) { const s = document.createElement("select"); for (const [v,l] of items) { const o=document.createElement("option");o.value=v;o.textContent=l;s.append(o); } s.value=value; s.addEventListener("change",()=>onChange(s.value)); return s; }
function field(label, control) { const w=document.createElement("label");w.className="field";const s=document.createElement("span");s.className="eyebrow";s.textContent=label;w.append(s,control);return w; }
function fmt(v, digits = 3) { if (v === null || v === undefined || Number.isNaN(Number(v))) return "—"; return Number(v).toFixed(digits).replace(/0+$/, "").replace(/\.$/, ""); }
function qid(s) { return escapeHtml(s); }
function escapeHtml(s) { return String(s ?? "").replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])); }
